### PR TITLE
fix plugin

### PR DESCRIPTION
**Pull request by LMBishop**
this is much better

### CODE REVIEW

**Comment by kacperleague9** [comment]
agreed

**Comment by JeffLegendPower** [comment]
fix plugin

**Comment by Dinty1** [comment]
🤔

**Comment by redaam** [comment]
m9, dat's gr9 work so gr9 
U Fuckin what? m9

**Comment by Jochyoua** [comment]
merge this already

**Comment by TheViperShow** [comment]
This change has not only greatly improved the performance of my server, but also made the players on it happier! I actually recommend the author to accept this change in their software because all users, from what I observe, have seen improvements in the performance of their server and the experience transmitted to their users. This patch is overall a very good job and I agree with the person who proposed it, who probably had to work for many hours doing hundreds of researches, so I hope it will be accepted. Moreover, the most amazing thing is that this change not only improves the performance of the server, but also the loading times! After installing this new version I've noticed that the build time of the project is reduced almost to zero, and the same goes for downloads and cloning of this project.

**Comment by OMGPandaYT** [comment]
fuck all of you.

**Comment by JeffLegendPower** [comment]
> This change has not only greatly improved the performance of my server, but also made the players on it happier! I actually recommend the author to accept this change in their software because all users, from what I observe, have seen improvements in the performance of their server and the experience transmitted to their users. This patch is overall a very good job and I agree with the person who proposed it, who probably had to work for many hours doing hundreds of researches, so I hope it will be accepted. Moreover, the most amazing thing is that this change not only improves the performance of the server, but also the loading times! After installing this new version I've noticed that the build time of the project is reduced almost to zero, and the same goes for downloads and cloning of this project.

I would like to add on to this detailed report of this pull request. Merging this would make the code far cleaner and many times more readable! Forking this is much less work and far easier to create a great addition to the anticheat. Please merge this as it would provide a multitude of benefits to any developer and server.

**Pull request closed without merging**
