### PR TITLE
You have to say 'This check made by t0206.'

### PR DESCRIPTION
**Pull request by BaGuAr**
so I added the lines.

※ if you wont to add lines . you have to remove the check or say sorry to him( t0206 )

### CODE REVIEW

**Comment by Waveium** [comment]
this kid sikds and trys to dox & ddos people. they most likely wont accept your pr but i hope they do

**Comment by OMGPandaYT** [comment]
> this kid sikds and trys to dox & ddos people. they most likely wont accept your pr but i hope they do

@Waveium i think you need to shut up. I have never ddosed someone, and the only "doxx" i did was my friend got my friend who is also their friends address and sent it in a group chat with only us and i sent it to the friend to ask if it was their ip. thats it. oh and then they tried doxxing me so LMAO

**Comment by OMGPandaYT** [comment]
I will be editing this pull request since your comment is not format correct and i technically did make part of this since i fixed loads of t0206's bugs.

**Comment by Waveium** [comment]
> > this kid sikds and trys to dox & ddos people. they most likely wont accept your pr but i hope they do
> 
> @Waveium i think you need to shut up. I have never ddosed someone, and the only "doxx" i did was my friend got my friend who is also their friends address and sent it in a group chat with only us and i sent it to the friend to ask if it was their ip. thats it. oh and then they tried doxxing me so LMAO

jxy. you did try to leak my address in yt comments.

**Comment by OMGPandaYT** [comment]
> > > this kid sikds and trys to dox & ddos people. they most likely wont accept your pr but i hope they do
> > 
> > 
> > @Waveium i think you need to shut up. I have never ddosed someone, and the only "doxx" i did was my friend got my friend who is also their friends address and sent it in a group chat with only us and i sent it to the friend to ask if it was their ip. thats it. oh and then they tried doxxing me so LMAO
> 
> jxy. you did try to leak my address in yt comments.

No you tried to leak my name by showing my nickname and middle name, then now i think u think "coco ritchie" is my name, its my dogs name, lol

**Pull request merged**
