### PR TITLE
Fixed some things

### PR DESCRIPTION
**Pull request by Jochyoua**
Reformatted
Added lombok functions
Fixed some mistakes
Remove KillAura because why move event? it false when walk, i can add back but like *why*

### CODE REVIEW

**Comment by OMGPandaYT** [comment]
if you saw the other pull request, this is for learning so i won't want to just steal any code.
Plus not removing killaura check because it detects if you killaura and then move the wrong direction too fast (If you use killaura and you run a direction your not meant to go with your yaw, it will flag that)

**Comment by Texboobcat** [comment]
Accepting a PR is not stealing code

**Comment by Jochyoua** [comment]
This isn't stealing code, I am giving you my consent to use this

**Comment by OMGPandaYT** [comment]
I know, but I don't want to use others code even if I have permission, that's what I mean. This is for me to learn, not for me to just use other peoples code. Because I won't understand that code and I won't be learning (probably).

**Pull request closed without merging**
