### PR TITLE
give proper credit

### PR DESCRIPTION
**Pull request by LaxWasHere**

### CODE REVIEW

**Comment by OMGPandaYT** [comment]
TheDoominator is no longer really contributing to this project.

**Comment by Jochyoua** [comment]
That honestly doesn't matter, you're using his code as a base and should credit him as such. You do on the spigot page but where his actual contributions are, they're invalid?

**Comment by Texboobcat** [comment]
hi

**Comment by JustDoom** [comment]
hi

**Comment by Jochyoua** [comment]
hi

**Comment by OMGPandaYT** [comment]
Wow. i took a hashmap example from an anticheat. I must now show him as an author because i took 3 lines of code!

**Comment by Texboobcat** [comment]
Now you are getting onto something! (A contributor on Github would suffice)

**Comment by Jochyoua** [comment]
hi

**Pull request closed without merging**
